                                                             session 14 and 15

Topics Covered:
1. ⯑ Introduction to NumPy
2. ⯑ Creating NumPy Arrays
3. ⯑ Array Dimensions & Shapes
4. ⯑ Array Indexing & Slicing
5. ⯑ Array Operations (Arithmetic & Logical)
6. ⯑ Universal Functions (ufuncs)
7. ⯑ Built-in NumPy Functions
8. ⯑ Random Module & Seeding
9. ⯑ Aggregate Functions: min, max, sum, mean, etc.
10. ⯑ Advanced Topics: reshape, flatten, stack, split, etc.
11. ⯑ Broadcasting
12. ⯑ Practical Examples & Summary

<h2 style="text-align: center;">🔑 Section 1: Introduction to Numpy</h2>

`NumPy` (Numerical Python) is the foundational package for numerical computing in Python. It provides support for:

- Multidimensional arrays and matrices
- Mathematical functions for array operations
- Efficient broadcasting and vectorization
  
We first import the library and check its version.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
list1=[0,1,2,3,4,5]
list1


[0, 1, 2, 3, 4, 5]

In [4]:
type(list1)

list

In [26]:
# Traditional Python List
import time
python_list = list(range(1, 1000001))
start = time.time()
python_result = [x * 2 for x in python_list]
end = time.time()
print("Time taken using Python list:", end - start, "seconds") # ➤ Slower
# NumPy Array
numpy_array = np.array(python_list)
start = time.time()
numpy_result = numpy_array * 2
end = time.time()
print("Time taken using NumPy array:", end - start, "seconds") # ➤ Faster

Time taken using Python list: 0.11351251602172852 seconds
Time taken using NumPy array: 0.003993034362792969 seconds


<h2 style="text-align: center;">🔑 Section 2: creating Numpy Arrays</h2>

`NumPy arrays` can be created using the np.array() function or other specialized
functions like `arange()` , `zeros()` , `ones()` , `linspace()` , etc.
We’ll explore:
- Creating 1D, 2D, and 3D arrays
- Specifying data types
- Using array-creation shortcuts

In [5]:
arr= np.array(list1)
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
print(type(arr))
print(type(list1))

<class 'numpy.ndarray'>
<class 'list'>


In [29]:
# Creating a 2D array
arr_2d = np.array([[1, 2], [3, 4]])
print("2D Array:\n", arr_2d)

2D Array:
 [[1 2]
 [3 4]]


In [30]:
# Creating a 3D array
arr_3d = np.array(
[
[[1, 2], [3, 4]],
[[5, 6], [7, 8]]
]
)
print("3D Array:\n", arr_3d)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Creating array with float data type
float_array = np.array([1, 2, 3], dtype=float)
print("Float Array:", float_array) # ➤ [1. 2. 3.]

Float Array: [1. 2. 3.]


In [40]:
print("Array of zeros:", np.zeros(5)) # ➤ [0. 0. 0. 0. 0.]
print("Array of ones:", np.ones((2, 3)))
# ➤ [[1. 1. 1.]
# [1. 1. 1.]]
print("Empty array (uninitialized):", np.empty(4))
# ➤ [random small numbers]
print("Range array:", np.arange(0, 10, 2)) # ➤ [0 2 4 6 8]
print("Linspace array:", np.linspace(0, 1, 5)) # ➤ [0. 0.25 0.5 0.75 1.

Array of zeros: [0. 0. 0. 0. 0.]
Array of ones: [[1. 1. 1.]
 [1. 1. 1.]]
Empty array (uninitialized): [0.25 0.5  0.75 1.  ]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


#### arange()
- The `arange()` function in Python is a part of the `NumPy library` and is used to create arrays with evenly spaced values within a specified interval.
- It is similar to Python's `built-in range()` function but returns a NumPy array instead of a list,
- making it more suitable for numerical computations and integration with other NumPy operations

In [7]:
np.arange(10)  # only 3 arguments allowed (start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [10]:
np.arange(10,30,3)  #we cant pass 4 arguments

array([10, 13, 16, 19, 22, 25, 28])

In [11]:
np.arange(20,8)   # 1st args must be less than 2nd args 

array([], dtype=int32)

In [12]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(-8,20) 

array([-8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(-20,8)# but when we use minus(-) 1st args can be greater

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [15]:
n=np.arange(8,20)
n

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [18]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [19]:
z=np.zeros((2,2))  #2d arrayx
z

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((3,2), dtype=int)


array([[0, 0],
       [0, 0],
       [0, 0]])

In [21]:
z=np.zeros((5,9), dtype=int)  # n-dimensional arrayx
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [24]:
np.ones((10,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [39]:
np.empty(4)

array([0.25, 0.5 , 0.75, 1.  ])

In [42]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [32]:
np.three(3) # error

AttributeError: module 'numpy' has no attribute 'three'

<h2 style="text-align: center;">🔑 Section 3 – Array Dimensions & Shapes</h2>


Understanding the `shape and dimensionality` of `NumPy arrays` is key to working with them efficiently.In this section, we’ll explore:
- `ndim` → number of dimensions
- `shape` → number of elements in each dimension
- `size` → total number of elements
- `reshape()` → changing the structure of arrays

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Dimensions (ndim):", arr.ndim) # ➤ 2
print("Shape:", arr.shape) # ➤ (2, 3)
print("Size:", arr.size) # ➤ 6
print("Data type:", arr.dtype) # ➤ int64 or int32 depending on system

Array:
 [[1 2 3]
 [4 5 6]]
Dimensions (ndim): 2
Shape: (2, 3)
Size: 6
Data type: int32


In [46]:
# Reshaping a 1D array to 2D
arr_1d = np.arange(12)
print("Original 1D array:", arr_1d)
arr_reshaped = arr_1d.reshape((3, 4))
print("Reshaped to 3x4:\n", arr_reshaped)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [47]:
reshaped = np.arange(15).reshape(5, 3)
print("Reshaped 5x3 Array:\n", reshaped)

Reshaped 5x3 Array:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### **To generate random number , use rand()**

In [33]:
random.rand()

0.28451712620830905

In [34]:
np.random.rand(2)

array([0.07770919, 0.33279199])

In [35]:
np.random.rand(3)

array([0.89411094, 0.7634935 , 0.91051608])

In [36]:
np.random.rand(2,3)

array([[0.19230981, 0.93763658, 0.52713052],
       [0.56402419, 0.87888153, 0.67595001]])

In [37]:
np.random.randint(3)

2

In [38]:
np.random.randint(2,10)

4

In [39]:
np.random.randint(2,10,4)

array([3, 3, 8, 5])

In [40]:
np.random.randint(-30,20,10)

array([-23, -22, -21,  -5,   1,   8,  -7,   9,  -4,  -8])

In [41]:
m=np.random.randint(10,40,(10,10))
m

array([[25, 12, 31, 38, 34, 27, 24, 31, 22, 21],
       [14, 23, 11, 23, 32, 10, 13, 25, 35, 11],
       [11, 14, 22, 38, 20, 35, 25, 16, 11, 20],
       [23, 22, 15, 16, 26, 28, 12, 14, 19, 10],
       [19, 34, 17, 33, 11, 18, 12, 21, 13, 39],
       [27, 20, 36, 32, 11, 25, 31, 27, 26, 19],
       [10, 30, 33, 22, 11, 26, 33, 36, 29, 39],
       [19, 24, 29, 39, 38, 27, 36, 14, 37, 32],
       [19, 31, 31, 19, 23, 18, 32, 11, 25, 14],
       [10, 38, 26, 15, 15, 31, 37, 22, 28, 39]])

In [42]:
arr

array([0, 1, 2, 3, 4, 5])

In [43]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [44]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [45]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

<h2 style="text-align: center;">🔑 Section 4 – Array Indexing & Slicing</h2>

Just like Python lists, NumPy arrays support:
- Indexing: Accessing individual elements
- Slicing: Accessing ranges/sub-arrays
- Works on 1D, 2D, and higher-dimensional arrays

We’ll now explore both techniques.

In [48]:
#Indexing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 0:", arr[0]) # ➤ 10
print("Element at index 3:", arr[3]) # ➤ 40
print("Last element (negative index):", arr[-1]) # ➤ 50

Element at index 0: 10
Element at index 3: 40
Last element (negative index): 50


In [49]:
#Indexing in 2D Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0, col 2:", arr_2d[0, 2]) # ➤ 3
print("Element at row 1, col 0:", arr_2d[1, 0]) # ➤ 4

Element at row 0, col 2: 3
Element at row 1, col 0: 4


In [ ]:
# Slicing in 1D Arrays
arr = np.array([10, 20, 30, 40, 50, 60])
print("Elements from index 1 to 4:", arr[1:5]) # ➤ [20 30 40 50]
print("Every 2nd element:", arr[::2]) # ➤ [10 30 50]
print("Reverse array:", arr[::-1])

In [51]:
# Slicing a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("First 2 rows:\n", arr_2d[:2])
# ➤ [[1 2 3]
# [4 5 6]]
print("First 2 columns:\n", arr_2d[:, :2])
# ➤ [[1 2]
# [4 5]
# [7 8]]
print("Bottom-right 2x2 block:\n", arr_2d[1:, 1:])
# ➤ [[5 6]
# [8 9]]

First 2 rows:
 [[1 2 3]
 [4 5 6]]
First 2 columns:
 [[1 2]
 [4 5]
 [7 8]]
Bottom-right 2x2 block:
 [[5 6]
 [8 9]]


#### slicing in matrix

In [46]:
m

array([[25, 12, 31, 38, 34, 27, 24, 31, 22, 21],
       [14, 23, 11, 23, 32, 10, 13, 25, 35, 11],
       [11, 14, 22, 38, 20, 35, 25, 16, 11, 20],
       [23, 22, 15, 16, 26, 28, 12, 14, 19, 10],
       [19, 34, 17, 33, 11, 18, 12, 21, 13, 39],
       [27, 20, 36, 32, 11, 25, 31, 27, 26, 19],
       [10, 30, 33, 22, 11, 26, 33, 36, 29, 39],
       [19, 24, 29, 39, 38, 27, 36, 14, 37, 32],
       [19, 31, 31, 19, 23, 18, 32, 11, 25, 14],
       [10, 38, 26, 15, 15, 31, 37, 22, 28, 39]])

In [47]:
b=np.random.randint(10,20,(5,4))
b

array([[17, 16, 10, 12],
       [18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14],
       [13, 18, 17, 12]])

In [48]:
b[:]

array([[17, 16, 10, 12],
       [18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14],
       [13, 18, 17, 12]])

In [49]:
b[1:4]

array([[18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14]])

In [50]:
b[-1:]

array([[13, 18, 17, 12]])

In [51]:
b[:-1]

array([[17, 16, 10, 12],
       [18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14]])

In [52]:
b[:-2]

array([[17, 16, 10, 12],
       [18, 16, 14, 15],
       [18, 13, 18, 15]])

In [53]:
b[1:4]

array([[18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14]])

In [54]:
b[1,2]

14

In [55]:
b


array([[17, 16, 10, 12],
       [18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14],
       [13, 18, 17, 12]])

In [56]:
b[1,3]

15

In [57]:
b[1:-1]


array([[18, 16, 14, 15],
       [18, 13, 18, 15],
       [15, 10, 14, 14]])

In [58]:
b[1,-1]

15

<h2 style="text-align: center;">Section 5 – Array Arithmetic & Logical Operations</h2>

NumPy allows element-wise operations on arrays, just like mathematical expressions.
These operations are vectorized, making them faster than Python loops.

We’ll cover:
- Arithmetic operations ( + , - , * , / , ** )
- Comparison operations ( == , != , > , < , etc.)
- Logical operations ( & , | , ~ )

In [52]:
# Arithmetic Operation
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Addition:", arr1 + arr2) # ➤ [5 7 9]
print("Subtraction:", arr2 - arr1) # ➤ [3 3 3]
print("Multiplication:", arr1 * arr2) # ➤ [ 4 10 18]
print("Division:", arr2 / arr1) # ➤ [4. 2.5 2.]
print("Exponentiation:", arr1 ** 2) # ➤ [1 4 9]

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Exponentiation: [1 4 9]


In [53]:
# Comparison Operations
print("Equal:", arr1 == arr2) # ➤ [False False False]
print("Not Equal:", arr1 != arr2) # ➤ [ True True True]
print("Greater:", arr2 > arr1) # ➤ [ True True True]

Equal: [False False False]
Not Equal: [ True  True  True]
Greater: [ True  True  True]


In [54]:
# Logical Operations
# Logical AND (element-wise)
print("Logical AND:", np.logical_and(arr1 > 0, arr2 > 4))
# ➤ [False True True]
# Logical OR
print("Logical OR:", np.logical_or(arr1 > 2, arr2 > 5))
# ➤ [False False True]
# Logical NOT
print("Logical NOT arr1 > 2:", np.logical_not(arr1 > 2))
# ➤ [ True True False]

Logical AND: [False  True  True]
Logical OR: [False False  True]
Logical NOT arr1 > 2: [ True  True False]


<h2 style="text-align: center;">Section 6 – NumPy Built-in Functions</h2>

NumPy comes with many powerful built-in functions that simplify numeric computation.
    
We’ll explore:
- Aggregation functions like sum() , min() , max() , mean() , std()
- Axis-specific operations
- Rounding, exponentials, and square roots

In [56]:
# aggregation functions like `sum()`, `min()`, `max()`, `mean()`, `std()`
# Aggregation functions are used to compute summary statistics over arrays.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Sum of all elements:", np.sum(arr)) # ➤ 21
print("Minimum value:", np.min(arr)) # ➤ 1
print("Maximum value:", np.max(arr)) # ➤ 6
print("Mean value:", np.mean(arr)) # ➤ 3.5
print("Standard deviation:", np.std(arr))

Sum of all elements: 21
Minimum value: 1
Maximum value: 6
Mean value: 3.5
Standard deviation: 1.707825127659933


In [57]:
print("Row-wise sum:", np.sum(arr, axis=1)) # ➤ [ 6 15]
print("Column-wise sum:", np.sum(arr, axis=0)) # ➤ [5 7 9]

Row-wise sum: [ 6 15]
Column-wise sum: [5 7 9]


In [58]:
arr = np.array([1.2, 2.5, 3.7])
print("Rounded values:", np.round(arr)) # ➤ [1. 2. 4.]
print("Square roots:", np.sqrt(arr)) # ➤ [1.095 1.581 1.923]
print("Exponentials:", np.exp(arr)) # ➤ [ 3.32 12.18 40.45]

Rounded values: [1. 2. 4.]
Square roots: [1.09544512 1.58113883 1.92353841]
Exponentials: [ 3.32011692 12.18249396 40.44730436]


In [59]:
arr

array([0, 1, 2, 3, 4, 5])

In [60]:
arr.max()

5

In [61]:
arr.min()

0

#### find mean, median 

In [62]:
from numpy import *  # 256 function called internally
a=array([1,2,3,4,9,])
median(a)

3.0

In [63]:
mean(a)

3.8

**Note**
- arr[2:10] - print the row from 2nd row to 9th row
- 2nd - starting index
- 10th - end index
- arr[2,10] - print specific no. not row which 2nd row and 10th col

#### Indexing in numpy

In [65]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
row=4
col=5

In [73]:
col

5

In [74]:
row

4

In [75]:
mat[row,col]

45

In [76]:
row=4
col=6

In [78]:
mat[row,col]

46

In [82]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
mat[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [80]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [81]:
mat[:,3]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [83]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
mat[::-1]  # reverse the matrix

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [86]:
mat[::-2] # step 2 

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [88]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [87]:
mat[2:6,2:4]  #(row,col)(2:6,2:4)

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [89]:
mat[1:2,2:4]

array([[12, 13]])

In [90]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

#### Masking or filter

In [91]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [95]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [96]:
mat[mat==50]

array([50])

In [97]:
mat[mat!=50]  # print all numbers except 50

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [1]:
print(True*2)

2


In [2]:
dict(range(9)) 

TypeError: cannot convert dictionary update sequence element #0 to a sequence

In [5]:
obj_data = ()
obj_data

()

<h2 style="text-align: center;">Section 7 – Array Copying & Views</h2>

In NumPy, assignment doesn’t create a new copy of an array &#8594; it creates a view
(reference).To truly copy an array, use the `.copy()` method.
We'll explore:
- Difference between `views` and `copies`
- How modifying one affects the other

In [59]:
original = np.array([10, 20, 30])
view = original # No copy, just a reference
view[0] = 99
print("Original after modifying view:", original) # ➤ [99 20 30]

Original after modifying view: [99 20 30]


In [60]:
original = np.array([10, 20, 30])
copy_array = original.copy()
copy_array[0] = 999
print("Original after modifying copy:", original) # ➤ [10 20 30]
print("Modified copy:", copy_array) # ➤ [999 20 30]

Original after modifying copy: [10 20 30]
Modified copy: [999  20  30]


In [61]:
arr_2d = np.array([[1, 2], [3, 4]])
copy_2d = arr_2d.copy()
copy_2d[0, 0] = 99
print("Original 2D:\n", arr_2d) # ➤ [[1 2], [3 4]]
print("Copied 2D:\n", copy_2d) # ➤ [[99 2], [3 4]]

Original 2D:
 [[1 2]
 [3 4]]
Copied 2D:
 [[99  2]
 [ 3  4]]


<h2 style="text-align:center;">Section 8 – Reshape, Flatten & Transpose</h2>

NumPy arrays offer powerful ways to manipulate their structure without changing
data:
- `reshape()` changes shape
- `flatten()` converts multi-D to 1D
- `transpose()` swaps axes (rows ↔ columns)

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3) # Convert 1D to 2x3 2D array
print("Original:", arr)
# ➤ [1 2 3 4 5 6]
print("Reshaped:\n", reshaped)
# ➤ [[1 2 3]
# [4 5 6]]

Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]


In [63]:
arr_2d = np.array([[10, 20], [30, 40]])
flat = arr_2d.flatten()
print("Flattened array:", flat)
# ➤ [10 20 30 40]

Flattened array: [10 20 30 40]


In [64]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
transposed = arr_2d.T
print("Original:\n", arr_2d)
# ➤ [[1 2 3]
# [4 5 6]]
print("Transposed:\n", transposed)
# ➤ [[1 4]
# [2 5]
# [3 6]]

Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


<h2 style="text-align:center;">Section 9 – Stacking and Splitting Arrays</h2>

NumPy allows combining and breaking arrays using functions like:
- `hstack()` → horizontal stacking
- `vstack()` → vertical stacking
- `split()` / hsplit() / vsplit() → for breaking arrays

In [65]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Horizontal stack (1D arrays become wider)
h = np.hstack((a, b))
print("Horizontal Stack:", h)
# ➤ [1 2 3 4 5 6]
# Vertical stack (1D arrays become rows)
v = np.vstack((a, b))
print("Vertical Stack:\n", v)
# ➤ [[1 2 3]
# [4 5 6]]

Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [66]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
# Stack along a new third axis
print("Stacked along depth (axis=2):\n", np.dstack((x, y)))
# ➤ [[[1 5]
# [2 6]]
# [[3 7]
# [4 8]]]

Stacked along depth (axis=2):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [67]:
arr = np.array([10, 20, 30, 40, 50, 60])
splitted = np.split(arr, 3)
print("Split into 3 parts:", splitted)
# ➤ [array([10, 20]), array([30, 40]), array([50, 60])]

Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]


<h2 style="text-align:center;">Section 10 – NumPy Random Module</h2>

NumPy provides a submodule called numpy.random to generate random numbers.
We’ll cover:
- Generating random integers, floats
- Random sampling from arrays
- Seeding for reproducibility

In [69]:
# Random integers between 1 and 10 (excluding 10)
rand_ints = np.random.randint(1, 10, size=5)
print("Random Integers:", rand_ints)
# ➤ e.g., [2 7 1 4 9]
# Random floats between 0 and 1
rand_floats = np.random.rand(3)
print("Random Floats:", rand_floats)
# ➤ e.g., [0.12 0.64 0.78]

Random Integers: [8 9 2 1 4]
Random Floats: [0.90134711 0.00275449 0.34368769]


In [70]:
arr = np.array([100, 200, 300, 400, 500])
sample = np.random.choice(arr, size=3)
print("Random sample:", sample)
# ➤ e.g., [200 500 100]

Random sample: [500 500 300]


In [71]:
np.random.seed(42)
print("Same output every time:", np.random.rand(3))
# ➤ [0.3745 0.9507 0.7319] – fixed due to seed

Same output every time: [0.37454012 0.95071431 0.73199394]


<h2 style="text-align:center;">Section 11 – NumPy Math & Utility Functions</h2>

NumPy provides many built-in math and utility functions, including:
- `np.sqrt()` , `np.exp()` , `np.log()` , `np.sin()` , `np.cos()`
- `np.unique()` , `np.sort()` , `np.where()` , `np.count_nonzero()`

In [73]:
arr = np.array([1, 4, 9, 16])
print("Square roots:", np.sqrt(arr)) # ➤ [1. 2. 3. 4.]
print("Exponential:", np.exp(arr)) # ➤ e.g., [2.7 54.6 ...]
print("Natural log:", np.log(arr)) # ➤ [0. 1.38 2.19 2.77]

Square roots: [1. 2. 3. 4.]
Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Natural log: [0.         1.38629436 2.19722458 2.77258872]


In [74]:
# Trigonometric Functions
angles = np.array([0, np.pi/2, np.pi])
print("sin:", np.sin(angles)) # ➤ [0. 1. 0.]
print("cos:", np.cos(angles)) # ➤ [1. 0. -1.]

sin: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos: [ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [75]:
# Utility Functions
arr = np.array([4, 2, 7, 2, 5, 7, 2])
print("Unique values:", np.unique(arr)) # ➤ [2 4 5 7]
print("Sorted array:", np.sort(arr)) # ➤ [2 2 2 4 5 7 7]
print("Index of 5s:", np.where(arr == 5)) # ➤ (array([4]),)
print("Count of non-zero elements:", np.count_nonzero(arr))

Unique values: [2 4 5 7]
Sorted array: [2 2 2 4 5 7 7]
Index of 5s: (array([4], dtype=int64),)
Count of non-zero elements: 7


In [76]:
arr = np.array([4, 2, 7, 2, 5, 7, 2])
print("Unique values:", np.unique(arr)) # ➤ [2 4 5 7]
print("Sorted array:", np.sort(arr)) # ➤ [2 2 2 4 5 7 7]
print("Index of 5s:", np.where(arr == 5)) # ➤ (array([4]),)
print("Count of non-zero elements:", np.count_nonzero(arr))

Unique values: [2 4 5 7]
Sorted array: [2 2 2 4 5 7 7]
Index of 5s: (array([4], dtype=int64),)
Count of non-zero elements: 7


#### PROGRAM TO GENERATE OTP

In [78]:
import numpy as np
otp = np.random.randint(0,6,4)
print(f"YOUR OTP IS {otp} . Please don't share with anyone")

YOUR OTP IS [2 2 4 3] . Please don't share with anyone


In [6]:
import random 
def generate_otp(length=4):
    ''' generate a numeric otp of a specified length.'''
    digits='012345'
    otp=''.join(random.choice(digits)for _ in range(length))
    return otp
#Example of usage
otp_length = 5 # we can change the length
otp = generate_otp(otp_length)
print(f"your OTP is: {otp}")


your OTP is: 40321


## `Cline` in vscode is AI tool which is used to develop application with in seconds

- just goto `extension` in `vscode`
- install `cline`
- type your task

### INTRODUCTION to `Streamlit` using `cmd`, `anaconda prompt` , `vs code` using below code to install

- `cmd` → pip install streamlit
- `anaconda prompt` → pip install streamlit 
- `vs code` → pip install streamlit

1. **browse `streamlit` in google.
2. **write below code in `notepad`**
- import streamlit as st
- st.write("My first app Hello *world ")
- save with `app.py`
- then open cmd, prompt, vs code terminal
- cd.., cd desktop (for change directory)
- write command `streamlit run app.py` in terminal